title:              Zachary Sanders
email:              zachsand@utexas.edu
description:        Personal website and blog
author:             Zachary Sanders
url:                "https://ZachSand.github.io"

# Social Profiles
github_username:    ZachSand
linkedin_username:  zachsanders

# Clean blog theme.
theme: jekyll-theme-clean-blog

# Google Analytics
google_analytics:   UA-180194380-1

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
